spring:
  application:
    name: pinyougou-sellgoods-service


dubbo:
  application:
    name: pinyougou-sellgoods-service
    id: pinyougou-sellgoods-service
  #  protocol:
  #    id: dubbo
  #    name: dubbo
  #    port: 20080
  #    threads: 10
  registry:
    id: my-register
    address: 47.98.132.138:2181
    protocol: zookeeper
    client: curator
    timeout: 30000
